# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastromateriais',
            name='precounitario',
            field=models.IntegerField(),
        ),
    ]
