# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_funcionario', '0003_auto_20170427_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastromateriais',
            name='precounitario',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
