# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastropedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(max_length=200)),
                ('quantidade', models.IntegerField(default=1)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.IntegerField()),
                ('numerodepedido', models.IntegerField(default=9999999, unique=True)),
            ],
        ),
    ]
