# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastropedido',
            name='status',
            field=models.CharField(default='aguardando', max_length=200),
        ),
    ]
