# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_cliente', '0002_cadastropedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastropedido',
            name='status',
            field=models.CharField(default='Aguardando', max_length=200),
        ),
    ]
